const form = {
  formId: "new-user-form",
  formField: {
    company: {
      name: "company",
      label: "Société",
      type: "text",
      placeholder: "exemple: Google",
      errorMsg: "Veuillez entrer un nom de société",
    },
    address: {
      name: "address",
      label: "Adresse",
      type: "text",
      placeholder: "exemple: 8 rue de la paix",
      errorMsg: "Veuillez indiquer une adresse.",
    },
    zipcode: {
      name: "zipcode",
      label: "Code postal",
      type: "number",
      placeholder: "75000",
      errorMsg: "Veuillez entrer un code postal.",
      invalidMsg: "Code postal non valide",
    },
    city: {
      name: "city",
      label: "Ville",
      type: "text",
      placeholder: "exemple: Paris",
      errorMsg: "Veuillez indiquer une ville.",
    },
    role: {
      name: "role",
      label: "Votre fonction",
      type: "text",
      placeholder: "exemple: Technicien",
      errorMsg: "Veuillez indiquer une fonction.",
    },
    first_name: {
      name: "first_name",
      label: "Prénom",
      type: "text",
      placeholder: "exemple: Pierre",
      errorMsg: "Veuillez indiquer vôtre prénom.",
    },
    last_name: {
      name: "last_name",
      label: "Nom",
      type: "text",
      placeholder: "exemple: Dupont",
      errorMsg: "Veuillez indiquer vôtre nom.",
    },
    shipping_alias: {
      name: "shipping_alias",
      label: "Alias de l'adresse de livraison",
      type: "text",
      placeholder: "exemple: Mon atelier",
      errorMsg: "Veuillez indiquer le nom de l'adresse.",
    },
    shipping_address: {
      name: "shipping_address",
      label: "Adresse de livraison",
      type: "text",
      placeholder: "exemple: 8 rue de la paix",
      errorMsg: "Veuillez entrer une adresse de livraison.",
    },
    shipping_zipcode: {
      name: "shipping_zipcode",
      label: "Code postal de livraison",
      type: "number",
      placeholder: "75000",
      errorMsg: "Veuillez entrer un code postal.",
      invalidMsg: "Code postal non valide.",
    },
    shipping_city: {
      name: "shipping_city",
      label: "Ville de livraison",
      type: "text",
      placeholder: "exemple: Lyon",
      errorMsg: "Veuillez indiquer une ville de livraison.",
    },
    phone_number: {
      name: "phone_number",
      label: "N° de téléphone",
      type: "text",
      placeholder: "+33612345678",
    },
  },
};

export default form;